#!/bin/bash
### BEGIN INIT INFO
#
# Provides: php-swoole
# Required-Start: 2 3 4 5
# Required-Stop: 0 1 6
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: PHP swoole/webroot/service.php nohup daemons initscript
# Description: This file should be placed in /etc/init.d
#
### END INIT INFO#

SCRIPT_NAME="php-swoole"
SCRIPT_PATH="/var/www/swoole/webroot"
SCRIPT_SRC="service.php"

PID_FILE="var/run/$SCRIPT_NAME.pid"

LOG_PATH="/var/log"

start() {
    if [ -e $PID_FILE ]; then
        echo "$SCRIPT_NAME is currently running!" 1>&2
        exit 1
    else
        nohup php $SCRIPT_PATH/$SCRIPT_SRC >> $LOG_PATH/$SCRIPT_NAME.log &
        echo "$SCRIPT_NAME started"
        echo $! > $PID_FILE
    fi
}

stop() {
    if [ -e $PID_FILE ]; then
        kill $(ps aux | grep "php $SCRIPT_PATH/$SCRIPT_SRC" | awk '{print $2}')
        rm $PID_FILE
        echo "$SCRIPT_NAME stopped"
    else
        echo "$SCRIPT_NAME not started!" 1>&2
        exit 1
    fi
}

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    status)
        systemctl status $SCRIPT_NAME
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload|status}" 1>&2
        exit 1
    ;;
esac
